[package]
name = "polynomial_commitment_scheme"
version = "0.1.0"
edition = "2021"

[dependencies]
ark-poly-commit = "0.5.0"
ark-bls12-381 = "0.5.0"
ark-ff = "0.5.0"
ark-ec = "0.5.0"
ark-poly = "0.5.0"
ark-bn254 = "0.5.0"
ark-std = "0.5.0"  # or ark-bls12-381

polynomials = { path = "../polynomials"}